### PR TITLE
`README`: Add set-up instructions

### PR DESCRIPTION
**Pull request by patbl**

### CODE REVIEW

**Comment by patbl** [comment]
I don't have much experience with Node projects so maybe some of the steps are not quite right.

**Comment by patbl** [comment]
Also, are there any easy-ish things I could work on? I'm interested in contributing.

**Comment by adam-binks** [comment]
Hi Patrick, thanks for contributing! For my dev db, I use a free Supabase database and set the DATABASE_URL in .env accordingly. I haven't tested the postgres steps, if it works for you then happy to merge this in.

**Comment by adam-binks** [comment]
Depending on what part of the project you're working on, you may need some other .env variables (e.g. if you're working on the Slackbot you'd need a SLACK_CLIENT_ID, SLACK_SIGNING_SECRET, etc). But this should be fine for now

**Comment by adam-binks** [comment]
> Also, are there any easy-ish things I could work on? I'm interested in contributing, but the open issues seem to be about big things that would benefit from familiarity with the code base.

Definitely! A few small things people have requested we add to fatebook.io that I would be excited to see added, if you're interested:

1. Show the number of resolved questions for each 10% interval on the calibration chart. Maybe when you mouse over one of the nodes we could add it to the tooltip
2. Exponentially weighted calibration chart: weight more recent predictions more heavily when calculating the user's calibration, so that you can improve it over time even with a long track record
3. In the "make a prediction" box (in the <Predict> component), you can add tags using hashtags, e.g. "Will trump win the election? #politics". However, currently this is not shown by the UI at all, and you have to type the full tag name. Ideally, when you type #, you'd see a selectable list of your existing tags, and as you type it would refine the list, similar to autocomplete in VS Code. This is probably a bit more work than the (1) and (2)

**Comment by patbl** [comment]
Thanks! Sorry for taking a while to get back to you.

> * Show the number of resolved questions for each 10% interval on the calibration chart. Maybe when you mouse over one of the nodes we could add it to the tooltip

Looks like this has since been implemented!

> Exponentially weighted calibration chart: weight more recent predictions more heavily when calculating the user's calibration, so that you can improve it over time even with a long track record

That's a good idea.

> In the "make a prediction" box (in the component), you can add tags using hashtags, e.g. "Will trump win the election? #politics". However, currently this is not shown by the UI at all, and you have to type the full tag name. Ideally, when you type #, you'd see a selectable list of your existing tags, and as you type it would refine the list, similar to autocomplete in VS Code. This is probably a bit more work than the (1) and (2)

I think I'll start off working on a hashtag bug, which is that hashtags are extracted even if there's no space before the `#`, so for example if you made a prediction that was

```
Patrick will reply to my comment: https://github.com/Sage-Future/fatebook/pull/12#issuecomment-1860376745T
```

it'll think `#issuecomment` is a hashtag, and the saved prediction text will be

```
Patrick will reply to my comment: https://github.com/Sage-Future/fatebook/pull/12-1860376745
```

This is pretty minor but I want to start off with something easy.

**Comment by adam-binks** [comment]
Great spot, thank you! Feel free to ping me here or on Discord (
https://discord.gg/mt9YVB8VDE) if I can help with anything. (It'd be useful
for me to hear about friction/confusion points for new contributors!)

**Comment by adam-binks** [comment]
Thank you @patbl for this! I've verified that these setup instructions work - I made some tweaks (added a shared OAuth credential so devs don't need to set up their own) and added this in d3b2fbc.

**Pull request closed without merging**
